site_name: 小博测试成长之路
theme:
  name: readthedocs
  show_powered_by: false
  code_font_size: 14
  theme_contrast: high
  font_family: "Helvetica, Arial, sans-serif"
  monospace_font: "Courier New, monospace"
  use_directory_urls: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition